#    ______               ______               
#   / ____/_  ______     / ____/_  ______      
#  / /_  / / / / __ \   / / __/ / / / __ \     
# / __/ / /_/ / / / /  / /_/ / /_/ / / / /     
#/_/    \__,_/_/ /_/   \____/\__,_/_/ /_/      
#                                  By [SeruXQ Development Team] discord.gg/tM9rJuAzUE

Discord: "discord.gg/tM9rJuAzUE"

Fun-Gun:
  Name: "&6Fun-Gun &7(Right-Click)" # Fun Gun name
  Join-Slot: 2  
  Cool-Down: 5
  Enable-Lore: true
  Lores:
    - ""
    - "&c&lSERUXQ DEVELOPMENT TEAM PASSED FROM HERE !"
    - ""
   
  
  
  
 